[project]
name = "vote"
version = "0.1.0"
description = "Small web application to accomplish votes."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

[tool.djlint]
max_blank_lines = 2
profile = "jinja"
